on:
  push:
    branches:
      - main

jobs:
  job-1:
    runs-on: ubuntu-latest
    concurrency:
      group: group-1
      cancel-in-progress: true

    steps:
      - name: Job1 and sleep 100s
        run: sleep 100s
        
  job-2:
    runs-on: ubuntu-latest
    concurrency:
      group: group-2
      cancel-in-progress: false

    steps:
      - name: Job1 and sleep 200s
        run: sleep 200s
